// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsW-r8rEkDyRdPp6D6TQ8KyDA3JnJJlpo',
    appId: '1:62814095959:android:d7d02c4a6b9f86a0f83112',
    messagingSenderId: '62814095959',
    projectId: 'we-chat-52cf2',
    storageBucket: 'we-chat-52cf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6avpWaSX60zsFXAr9oH7nuM475IBA28U',
    appId: '1:62814095959:ios:bc2043525e69bb12f83112',
    messagingSenderId: '62814095959',
    projectId: 'we-chat-52cf2',
    storageBucket: 'we-chat-52cf2.appspot.com',
    androidClientId: '62814095959-1gjli8fjl5899m0gisd8g0jrc489sr79.apps.googleusercontent.com',
    iosClientId: '62814095959-fl92eg1go5mikq0rlk1v36v43o2ejahb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechatApp',
  );
}
